# Generated by Django 4.2.7 on 2025-04-17 06:53

from django.db import migrations, models
import translator_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MangaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Título')),
                ('original_image', models.ImageField(upload_to=translator_app.models.get_upload_path, verbose_name='Imagen Original')),
                ('translated_image', models.ImageField(blank=True, null=True, upload_to=translator_app.models.get_result_path, verbose_name='Imagen Traducida')),
                ('source_language', models.CharField(choices=[('ja', 'Japonés'), ('ko', 'Coreano'), ('zh', 'Chino'), ('auto', 'Detectar automáticamente')], default='auto', max_length=10, verbose_name='Idioma de origen')),
                ('target_language', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='es', max_length=10, verbose_name='Idioma de destino')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('detected_text', models.JSONField(blank=True, null=True, verbose_name='Texto detectado')),
                ('translated_text', models.JSONField(blank=True, null=True, verbose_name='Texto traducido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Página de Manga',
                'verbose_name_plural': 'Páginas de Manga',
                'ordering': ['-created_at'],
            },
        ),
    ]
